# Server configuration
server:
  port: 8080

# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC
    username: todolist
    password: kXaj@3ix
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Initialize schema
  sql:
    init:
      mode: always

  # Swagger Configuration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # JPA/Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# Logging configuration
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# Swagger UI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  packages-to-scan: io.github.px1d.controller
  paths-to-match: /api/**

jwt:
  secret: 6jv1ji2jk+xk2+^ajo--ifd
  expiration: 86400000  # 24 hours in milliseconds
